services:
  database:
    image: mysql:lts
    command: --secure-file-priv='' --local-infile=1
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: analytics
    volumes:
      - ./mysql_storage:/var/lib/mysql
      - ./datasets:/var/lib/mysql-files/
